# Generated by Django 4.2.13 on 2024-05-29 09:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='CurriculumEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum')),
                ('evaluation_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.evaluationcriterion')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
