# Generated by Django 4.2.13 on 2024-05-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_comment_content_alter_syllabus_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumevaluation',
            name='curriculum',
        ),
    ]
