# Generated by Django 4.2.13 on 2024-05-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_evaluationcriterion_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='curriculums',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum'),
        ),
    ]
