# Generated by Django 4.2.13 on 2024-06-12 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_syllabus_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images/avatar/%Y/%m/%d/'),
        ),
    ]
