# Generated by Django 4.2.13 on 2024-06-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_evaluationcriterion_courses_alter_syllabus_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcriterion',
            name='courses',
        ),
    ]
