# Generated by Django 4.2.13 on 2024-06-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_evaluationcriterion_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcriterion',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='evaluationcriterion',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
