# Generated by Django 4.2.13 on 2024-06-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_curriculumevaluation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcriterion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationcriterion',
            unique_together={('course', 'name')},
        ),
    ]
